plugins {
    id 'java'
    id("io.freefair.lombok") version "9.2.0"
}

group 'com.kit'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
}

sourceCompatibility = '17'
targetCompatibility = '17'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

dependencies {
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.25.0'
    testImplementation 'io.rest-assured:rest-assured:6.0.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.3'
    testImplementation 'tools.jackson.core:jackson-core:3.0.4'
    testImplementation 'tools.jackson.core:jackson-databind:3.0.4'
    testImplementation 'com.fasterxml.jackson.core:jackson-annotations:2.21'
    implementation 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'

}

test {
    useJUnitPlatform()
}